# Generated by Django 5.2.8 on 2025-11-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='meta_description',
            field=models.TextField(blank=True, help_text='A brief description for search engines (150-160 characters recommended)'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Override the default page title for SEO', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='meta_description',
            field=models.TextField(blank=True, help_text='A brief description for search engines (150-160 characters recommended)'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Override the default page title for SEO', max_length=255),
        ),
    ]
