# Generated by Django 5.2.8 on 2025-12-04 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogindexpage_meta_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='feed_image',
        ),
    ]
