# Generated by Django 5.2.8 on 2025-11-29 13:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_standardpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standardpage',
            options={'verbose_name': 'Standard Page', 'verbose_name_plural': 'Standard Pages'},
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
